[project]
name = "blog-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.6.0",
    "python-dotenv>=1.1.1",
    "unsloth>=2025.6.8",
]
